### ISSUE TITLE
apollo useQuery hook.

### ISSUE THREAD

**Issue by El-Mehdi-Abdi** [vuejs/vue-apollo#840]
This file is for all apollo hooks: **useQuery**, useMutation, useSubscribe..
**apollo-hooks.js**

**App.vue**
usage in your app.vue you have to provide context to appolo then u can use its hooks in all chld components like honey.
i hop this help you add this feature. its light .

https://gist.github.com/El-Mehdi-Abdi/137f128319c32d5dd53667b4ecd0918d

**Comment by Austio** [comment]
For anyone looking at this, i'm sure we will get this in vue-apollo sometime due to Guillaume Chau's work on composition api having ssr support .  In the meantime i have a working example that has what i think is a good interface that we can build on 

https://github.com/Austio/apollo-hooks-vue/blob/master/src/useQuery.js
Going to publish it roughly under `apollo-vue-hooks` so that we can have some iteration on this in the community before we decide on the api that is needed
